- name: Update IBP ssl
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Git update
      git:
        repo: 'git@github.com:GATOTECH-LTD/ibp-ssl.git'
        dest: '/root/github/ibp-ssl'
        key_file: '/root/.ssh/ibp-key'
        update: yes
    - name: Create certificate file for HAProxy for ibp.network
      shell: cat /root/github/ibp-ssl/cert/fullchain.pem /root/github/ibp-ssl/cert/privkey.pem > /root/github/ibp-ssl/cert/ibp.network.pem
    - name: "Check new expiration date"
      shell: "openssl x509 -enddate -noout -in /root/github/ibp-ssl/cert/cert.pem | cut -f2 -d'='"
      register: expiration_date_new_ibp
- name: Update Dotters ssl
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Git update
      git:
        repo: 'git@github.com:senseless/dotters-ssl.git'
        dest: '/root/github/dotters-ssl'
        key_file: '/root/.ssh/dotters-key'
        update: yes
    - name: Create certificate file for HAProxy for dotters.network
      shell: cat /root/github/dotters-ssl/cert/fullchain.pem /root/github/dotters-ssl/cert/privkey.pem > /root/github/dotters-ssl/cert/dotters.network.pem
    - name: "Check new expiration date"
      shell: "openssl x509 -enddate -noout -in /root/github/dotters-ssl/cert/cert.pem | cut -f2 -d'='"
      register: expiration_date_new_dotters
- name: Update Load Balancer SSL
  remote_user: ansible
  hosts: rpc_balancers
  become: yes
  tasks:
    - name: Transfer Certificate
      copy:
        src=/root/github/ibp-ssl/cert/ibp.network.pem
        dest=/etc/pki/certs/ibp.network.pem
        owner=root
        group=root
        mode=0644
        force=yes
    - name: Transfer Certificate
      copy:
        src=/root/github/dotters-ssl/cert/dotters.network.pem
        dest=/etc/pki/certs/dotters.network.pem
        owner=root
        group=root
        mode=0644
        force=yes
- name: Reload HAProxy to read new cert
  hosts: rpc_balancers
  remote_user: ansible
  become: yes
  tasks:
    - name: Restart haproxy
      service: name=haproxy state=restarted
